# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            t(h)inker
tagline:          'hmm'
description:      'Dự án thử nghiệm 3 tháng với chủ đề Hẹn hò ở Thành phố Hồ Chí Minh, Việt Nam.'
url:              http://facebook.com/saigondatingproject/
baseurl:          /

author:
  name:           'Nguyễn Mai Hương'
  url:            https://github.com/ngmaihuong

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ngmaihuong/saigondatingproject-su20
