title: t(h)inker
logo: /assets/img/Logo Black.png
description: Dự án thử nghiệm 3 tháng với chủ đề Hẹn hò ở Sài Gòn, Việt Nam. 
show_downloads: false
theme: jekyll-theme-minimal

#author: Nguyễn Mai Hương
#email: maihuongnguyen1603@gmail.com
#description: > # this means to ignore newlines until "baseurl:"
#theme: jekyll-theme-minimal

# social links
#facebook_username: heydudeimneko
#github_username:  ngmaihuong

#show_excerpts: false # set to false to remove excerpts on the homepage
