title: Is 0 a number?
author: Nguyễn Mai Hương
email: maihuongnguyen1603@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello hello!
theme: minima

# social links
facebook_username: heydudeimneko
github_username:  ngmaihuong

show_excerpts: false # set to false to remove excerpts on the homepage
